export const PROJECTS = [
  {
    title: "Portfolio Website",
    description: "A personal portfolio website built with Next.js and Tailwind CSS.",
    image: "/placeholder.svg?height=400&width=600",
    github: "https://github.com/yourusername/portfolio",
    live: "https://yourportfolio.com",
    tags: ["Next.js", "React", "Tailwind CSS"],
  },
  {
    title: "E-commerce Platform",
    description: "A full-stack e-commerce platform with payment integration.",
    image: "/placeholder.svg?height=400&width=600",
    github: "https://github.com/yourusername/ecommerce",
    live: "https://yourecommerce.com",
    tags: ["React", "Node.js", "MongoDB", "Stripe"],
  },
  {
    title: "Task Management App",
    description: "A collaborative task management application with real-time updates.",
    image: "/placeholder.svg?height=400&width=600",
    github: "https://github.com/yourusername/taskmanager",
    live: "https://yourtaskmanager.com",
    tags: ["React", "Firebase", "Redux", "Material UI"],
  },
  {
    title: "Weather Dashboard",
    description: "A weather dashboard that displays current and forecasted weather data.",
    image: "/placeholder.svg?height=400&width=600",
    github: "https://github.com/yourusername/weather",
    live: "https://yourweather.com",
    tags: ["JavaScript", "OpenWeather API", "Chart.js"],
  },
  {
    title: "Social Media Analytics",
    description: "A tool for tracking and analyzing social media engagement metrics.",
    image: "/placeholder.svg?height=400&width=600",
    github: "https://github.com/yourusername/socialanalytics",
    live: "https://yoursocialanalytics.com",
    tags: ["React", "D3.js", "Node.js", "Express"],
  },
  {
    title: "Recipe Finder",
    description: "An application that helps users find recipes based on available ingredients.",
    image: "/placeholder.svg?height=400&width=600",
    github: "https://github.com/yourusername/recipefinder",
    live: "https://yourrecipefinder.com",
    tags: ["React", "Spoonacular API", "Tailwind CSS"],
  },
]

