import './globals.css'
import type { Metadata } from 'next'
import { Zilla_Slab } from 'next/font/google'

const zillaSlab = Zilla_Slab({weight: ['300', '400', '500', '600', '700'], subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={zillaSlab.className}>{children}</body>
    </html>
  )
}
